---

- name: "Determine each user's HOME directory"
  become: true
  pyenv_users_home:
    users: "{{ pyenv_users | map(attribute='username') | list}}"
  when: >
    pyenv_users is iterable
  tags:
    - pyenv
    - user
    - home
