---

# Configure any necessary repositories used to install recent version of GIT
- include_tasks: repository_install.yml
  
# Install pyenv build dependencies
- include_tasks: build_dependencies_install.yml
  
# Install pyenv git dependencies
- include_tasks: git_dependencies_install.yml

# Install per user pyenv
- include_tasks: pyenv_install.yml

# Install per user pyenv-virtualenv module
- include_tasks: pyenv_virtualenv_install.yml

# Install per user Python environments
- include_tasks: pyenvs_install.yml

# Install per user Python virtualenvs
- include_tasks: pyenv_virtualenvs_install.yml

# Install per user shell environment configuration to autoload pyenv
- include_tasks: pyenv_shell_env_install.yml
