---

- include_tasks: utils/users_home.yml

- name: Uninstall per user pyenv-virtualenv module
  become: true
  become_user: "{{ pyenv_user.username }}"
  loop_control:
    loop_var: pyenv_user
  file:
    # Use the destination as is if its absolute or the user's HOME directory is not known, otherwise append the path to the user's HOME directory    
    dest: "{{ (pyenv_user.pyenv_dest | is_abs or pyenv_users_home[pyenv_user.username] is not defined) | ternary(pyenv_user.pyenv_dest, [pyenv_users_home[pyenv_user.username], pyenv_user.pyenv_dest] | join('/')) }}/plugins/pyenv-virtualenv"
    state: absent
  register: pyenv_virtualenv_status
  with_items: "{{ pyenv_users }}"
  when: >
    pyenv_users is iterable and
    pyenv_user is mapping and
    pyenv_user.plugins is iterable and
    pyenv_user.pyenv_dest is defined and
    pyenv_user.username is defined and
    'pyenv-virtualenv' in pyenv_user.plugins
  tags:
    - pyenv-virtualenv
    - user
