---

- name: Uninstall per user pyenv
  become: true
  become_user: "{{ pyenv_user.username }}"
  loop_control:
    loop_var: pyenv_user
  pyenv:
    dest: "{{ pyenv_user.pyenv_dest }}"
    state: absent
  register: pyenv_pyenv_status
  with_items: "{{ pyenv_users }}"
  when: >
    pyenv_users is iterable and
    pyenv_user is mapping and
    pyenv_user.pyenv_dest is defined and
    pyenv_user.username is defined
  tags:
    - pyenv
    - user
