---

# Remove per user shell environment configuration to autoload pyenv
- include_tasks: pyenv_shell_env_uninstall.yml

# Remove per user Python virtualenvs
- include_tasks: pyenv_virtualenvs_uninstall.yml

# Remove per user Python environments
- include_tasks: pyenvs_uninstall.yml

# Remove per user pyenv-virtualenv module
- include_tasks: pyenv_virtualenv_uninstall.yml

# Remove per user pyenv
- include_tasks: pyenv_uninstall.yml

# Remove pyenv git dependencies
- include_tasks: git_dependencies_uninstall.yml

# Remove pyenv build dependencies
- include_tasks: build_dependencies_uninstall.yml

# Remove any necessary repositories used to install recent version of GIT
- include_tasks: repository_uninstall.yml
