---

- name: Manage pyenv build dependencies
  become: true
  loop_control:
    loop_var: pyenv_build_dependency
  dnf:
    conf_file:         "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.conf_file | default(omit) }}"
    disable_gpg_check: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.disable_gpg_check | default(omit) }}"
    disablerepo:       "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.disablerepo | default(omit) }}"
    enablerepo:        "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.enablerepo | default(omit) }}"
    installroot:       "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.installroot | default(omit) }}"
    name:              "{{ pyenv_build_dependency }}"
    state:             "{{ pyenv_build_dependencies_state }}"
  register: pyenv_build_dependencies_status
  with_items: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages }}"
  when: >
    hostvars[inventory_hostname].ansible_distribution == 'Fedora' and
    (hostvars[inventory_hostname].ansible_distribution_major_version | int) >= 22 and
    pyenv_build_dependencies is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution] is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages is iterable and
    pyenv_build_dependencies_state is defined
  tags:
    - dependencies
