---

- name: Manage pyenv build dependencies
  become: true
  loop_control:
    loop_var: pyenv_build_dependency
  zypper:
    disable_gpg_check:  "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.disable_gpg_check | default(omit) }}"
    disable_recommends: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.disable_recommends | default(omit) }}"
    force:              "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.force | default(omit) }}"
    name:               "{{ pyenv_build_dependency }}"
    old_package:        "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.old_package | default(omit) }}"
    state:              "{{ pyenv_build_dependencies_state }}"
    update_cache:       "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.update_cache | default(omit) }}"
  register: pyenv_build_dependencies_status
  with_items: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages }}"
  when: >
    hostvars[inventory_hostname].ansible_os_family == 'Suse' and
    pyenv_build_dependencies is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution] is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages is iterable and
    pyenv_build_dependencies_state is defined
  tags:
    - dependencies
