---

- name: Manage pyenv build dependencies
  become: true
  loop_control:
    loop_var: pyenv_build_dependency
  apt:
    allow_unauthenticated: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.allow_unauthenticated | default(omit) }}"
    cache_valid_time:      "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.cache_valid_time | default(omit) }}"
    default_release:       "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.default_release | default(omit) }}"
    force:                 "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.force | default(omit) }}"
    install_recommends:    "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.install_recommends | default(omit) }}"
    name:                  "{{ pyenv_build_dependency }}"
    only_upgrade:          "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.only_upgrade | default(omit) }}"
    purge:                 "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.purge | default(omit) }}"
    state:                 "{{ pyenv_build_dependencies_state }}"
    update_cache:          "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.update_cache | default(omit) }}"
  register: pyenv_build_dependencies_status
  with_items: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages }}"
  when: >
    hostvars[inventory_hostname].ansible_os_family in ['Debian', 'Linuxmint'] and
    pyenv_build_dependencies is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution] is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages is iterable and
    pyenv_build_dependencies_state is defined
  tags:
    - dependencies
