---

- name: Manage pyenv build dependencies
  become: true
  loop_control:
    loop_var: pyenv_build_dependency
  apk:
    name:         "{{ pyenv_build_dependency }}"
    state:        "{{ pyenv_build_dependencies_state }}"
    update_cache: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager.update_cache | default(omit) }}"
  with_items: "{{ pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages }}"
  register: pyenv_build_dependencies_status
  when: >
    hostvars[inventory_hostname].ansible_distribution == 'Alpine' and
    pyenv_build_dependencies is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution] is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].package_manager is mapping and
    pyenv_build_dependencies[hostvars[inventory_hostname].ansible_distribution].packages is iterable and
    pyenv_build_dependencies_state is defined
  tags:
    - dependencies
